# Generated by Django 2.1.7 on 2019-04-17 03:42

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=150, verbose_name='name (in English)')),
                ('name_es', models.CharField(max_length=150, verbose_name='name (in Spanish)')),
                ('name_pt_BR', models.CharField(max_length=150, verbose_name='name (in Portuguese)')),
                ('slug_en', models.SlugField(max_length=150, unique=True, verbose_name='slug (in English)')),
                ('slug_es', models.SlugField(max_length=150, unique=True, verbose_name='slug (in Spanish)')),
                ('slug_pt_BR', models.SlugField(max_length=150, unique=True, verbose_name='slug (in Portuguese)')),
                ('short_desc_en', models.TextField(blank=True, help_text="Only necessary if it's a combo.", max_length=200, verbose_name='short description (in English)')),
                ('short_desc_es', models.TextField(blank=True, help_text="Only necessary if it's a combo.", max_length=200, verbose_name='short description (in Spanish)')),
                ('short_desc_pt_BR', models.TextField(blank=True, help_text="Only necessary if it's a combo.", max_length=200, verbose_name='short description (in Portuguese)')),
                ('available', models.BooleanField(default=True, verbose_name='available')),
                ('combo', models.BooleanField(default=False, verbose_name='Is it tour combo?')),
                ('combo_discount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Per passenger.', max_digits=10, verbose_name='combo discount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Category / Combo',
                'verbose_name_plural': 'Categories / Combos',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(db_index=True, max_length=150, verbose_name='name (in English)')),
                ('name_es', models.CharField(db_index=True, max_length=150, verbose_name='name (in Spanish)')),
                ('name_pt_BR', models.CharField(db_index=True, max_length=150, verbose_name='name (in Portuguese)')),
                ('icon', models.CharField(default='fa-eye', help_text='String from Font Awesome icons e.g. "fa-eye"', max_length=150, verbose_name='icon')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'feature',
                'verbose_name_plural': 'features',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='name')),
                ('region', models.CharField(blank=True, db_index=True, help_text='Helps users to search by coincidence.', max_length=150, verbose_name='region')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'locations',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(db_index=True, max_length=150, verbose_name='name (in English)')),
                ('name_es', models.CharField(db_index=True, max_length=150, verbose_name='name (in Spanish)')),
                ('name_pt_BR', models.CharField(db_index=True, max_length=150, verbose_name='name (in Portuguese)')),
                ('available', models.BooleanField(default=True, verbose_name='available')),
                ('tour_type', models.CharField(choices=[('HALF', 'Half-Day'), ('FULL', 'Full-Day')], max_length=4, verbose_name='type of tour')),
                ('slug_en', models.SlugField(max_length=150, unique=True, verbose_name='slug (in English)')),
                ('slug_es', models.SlugField(max_length=150, unique=True, verbose_name='slug (in Spanish)')),
                ('slug_pt_BR', models.SlugField(max_length=150, unique=True, verbose_name='slug (in Portuguese)')),
                ('description_en', models.TextField(verbose_name='tour description (in English)')),
                ('description_es', models.TextField(verbose_name='tour description (in Spanish)')),
                ('description_pt_BR', models.TextField(verbose_name='tour description (in Portuguese)')),
                ('duration', models.PositiveSmallIntegerField(verbose_name='duration (in hours)')),
                ('min_pax_number', models.PositiveSmallIntegerField(default=1, verbose_name='minimum passenger number')),
                ('adult_reg_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="adults' regular price")),
                ('children_reg_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="children's regular price")),
                ('adult_sale_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name="adults' sale price")),
                ('children_sale_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name="children's sale price")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('categories', models.ManyToManyField(blank=True, related_name='tours', related_query_name='tour', to='raidchileapp.Category', verbose_name='categories')),
                ('features', models.ManyToManyField(blank=True, related_name='tours', related_query_name='tour', to='raidchileapp.Feature', verbose_name='features')),
                ('locations', models.ManyToManyField(blank=True, related_name='tours', related_query_name='tour', to='raidchileapp.Location', verbose_name='locations')),
            ],
            options={
                'verbose_name': 'tour',
                'verbose_name_plural': 'tours',
                'ordering': ('name_es',),
            },
        ),
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternative_en', models.CharField(help_text='Image description in English.', max_length=150, verbose_name='alternative text (in English)')),
                ('alternative_es', models.CharField(db_index=True, help_text='Image description in Spanish.', max_length=150, verbose_name='alternative text (in Spanish)')),
                ('alternative_pt_BR', models.CharField(help_text='Image description in Portuguese.', max_length=150, verbose_name='alternative text (in Portuguese)')),
                ('image', models.ImageField(upload_to='tours_images/%Y/%m/%d', verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('tours', models.ManyToManyField(blank=True, related_name='images', related_query_name='image', to='raidchileapp.Tour')),
            ],
            options={
                'verbose_name': 'tour image',
                'verbose_name_plural': 'tour images',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', related_query_name='category', to='raidchileapp.TourImage', verbose_name='image'),
        ),
    ]
