# Generated by Django 2.1.7 on 2019-04-18 18:31

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=150, verbose_name='name (in English)')),
                ('name_es', models.CharField(max_length=150, verbose_name='name (in Spanish)')),
                ('name_pt_BR', models.CharField(max_length=150, verbose_name='name (in Portuguese)')),
                ('slug_en', models.SlugField(max_length=150, unique=True, verbose_name='slug (in English)')),
                ('slug_es', models.SlugField(max_length=150, unique=True, verbose_name='slug (in Spanish)')),
                ('slug_pt_BR', models.SlugField(max_length=150, unique=True, verbose_name='slug (in Portuguese)')),
                ('available', models.BooleanField(default=True, verbose_name='available')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('name_es',),
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(db_index=True, max_length=150, verbose_name='name (in English)')),
                ('name_es', models.CharField(db_index=True, max_length=150, verbose_name='name (in Spanish)')),
                ('name_pt_BR', models.CharField(db_index=True, max_length=150, verbose_name='name (in Portuguese)')),
                ('icon', models.CharField(default='fa-eye', help_text='String from Font Awesome icons e.g. "fa-eye"', max_length=150, verbose_name='icon')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'feature',
                'verbose_name_plural': 'features',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='name')),
                ('region', models.CharField(blank=True, db_index=True, help_text='Helps users to search by coincidence.', max_length=150, verbose_name='region')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'locations',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(db_index=True, max_length=150, verbose_name='name (in English)')),
                ('name_es', models.CharField(db_index=True, max_length=150, verbose_name='name (in Spanish)')),
                ('name_pt_BR', models.CharField(db_index=True, max_length=150, verbose_name='name (in Portuguese)')),
                ('available', models.BooleanField(default=True, verbose_name='available')),
                ('slug_en', models.SlugField(max_length=150, unique=True, verbose_name='slug (in English)')),
                ('slug_es', models.SlugField(max_length=150, unique=True, verbose_name='slug (in Spanish)')),
                ('slug_pt_BR', models.SlugField(max_length=150, unique=True, verbose_name='slug (in Portuguese)')),
                ('product_type', models.CharField(choices=[('TOUR', 'Tour'), ('COMBO', 'Combo')], max_length=5, verbose_name='type of product')),
                ('description_en', models.TextField(help_text='Long if tour. Short if Combo.', verbose_name='description (in English)')),
                ('description_es', models.TextField(help_text='Long if tour. Short if Combo.', verbose_name='description (in Spanish)')),
                ('description_pt_BR', models.TextField(help_text='Long if tour. Short if Combo.', verbose_name='description (in Portuguese)')),
                ('min_pax_number', models.PositiveSmallIntegerField(default=1, verbose_name='minimum passenger number')),
                ('adult_reg_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name="adults' regular price")),
                ('children_reg_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name="children's regular price")),
                ('adult_sale_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name="adults' sale price")),
                ('children_sale_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name="children's sale price")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
        ),
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternative_en', models.CharField(help_text='Image description in English.', max_length=150, verbose_name='alternative text (in English)')),
                ('alternative_es', models.CharField(db_index=True, help_text='Image description in Spanish.', max_length=150, verbose_name='alternative text (in Spanish)')),
                ('alternative_pt_BR', models.CharField(help_text='Image description in Portuguese.', max_length=150, verbose_name='alternative text (in Portuguese)')),
                ('image', models.ImageField(upload_to='tours_images/%Y/%m/%d', verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'tour image',
                'verbose_name_plural': 'tour images',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='raidchileapp.Product')),
            ],
            options={
                'verbose_name': 'Tour',
                'verbose_name_plural': 'Tours',
                'ordering': ('-created_at',),
            },
            bases=('raidchileapp.product',),
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='raidchileapp.Product')),
                ('duration_type', models.CharField(choices=[('HALF', 'Half-Day'), ('FULL', 'Full-Day')], max_length=4, verbose_name='type of tour')),
                ('duration', models.PositiveSmallIntegerField(verbose_name='duration (in hours)')),
                ('features', models.ManyToManyField(blank=True, related_name='tours', related_query_name='tour', to='raidchileapp.Feature', verbose_name='features')),
                ('locations', models.ManyToManyField(blank=True, related_name='tours', related_query_name='tour', to='raidchileapp.Location', verbose_name='locations')),
            ],
            options={
                'verbose_name': 'Tour',
                'verbose_name_plural': 'Tours',
                'ordering': ('-created_at',),
            },
            bases=('raidchileapp.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', related_query_name='product', to='raidchileapp.Category', verbose_name='categories'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', related_query_name='category', to='raidchileapp.TourImage', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='tourimage',
            name='tours',
            field=models.ManyToManyField(blank=True, related_name='images', related_query_name='image', to='raidchileapp.Tour'),
        ),
        migrations.AddField(
            model_name='combo',
            name='tours',
            field=models.ManyToManyField(related_name='combos', related_query_name='combo', to='raidchileapp.Tour', verbose_name='Tours included in the combo'),
        ),
    ]
