# Generated by Django 2.1.7 on 2019-04-18 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raidchileapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='combo',
            options={'ordering': ('-created_at',), 'verbose_name': 'Tour Combo', 'verbose_name_plural': 'Tour Combos'},
        ),
        migrations.AddField(
            model_name='combo',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combos', related_query_name='combo', to='raidchileapp.TourImage', verbose_name='image'),
        ),
    ]
