# Generated by Django 2.1.7 on 2019-04-04 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raidchileapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', related_query_name='category', to='raidchileapp.TourImage'),
        ),
        migrations.RemoveField(
            model_name='tour',
            name='category',
        ),
        migrations.AddField(
            model_name='tour',
            name='category',
            field=models.ManyToManyField(related_name='tours', related_query_name='tour', to='raidchileapp.Category'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(verbose_name='tour description'),
        ),
    ]
