# Generated by Django 2.1.7 on 2019-04-18 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raidchileapp', '0002_auto_20190418_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='locations',
        ),
        migrations.AddField(
            model_name='product',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='products', related_query_name='product', to='raidchileapp.Location', verbose_name='locations'),
        ),
        migrations.AlterField(
            model_name='combo',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Appears in the homepage.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combos', related_query_name='combo', to='raidchileapp.TourImage', verbose_name='image'),
        ),
    ]
