# Generated by Django 2.1.7 on 2019-04-06 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raidchileapp', '0002_auto_20190404_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='category',
            new_name='categories',
        ),
    ]
