# Generated by Django 2.1.7 on 2019-04-06 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raidchileapp', '0003_auto_20190406_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='tours', related_query_name='tour', to='raidchileapp.Category'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='tours', related_query_name='tour', to='raidchileapp.Feature'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='tours', related_query_name='tour', to='raidchileapp.Location'),
        ),
        migrations.AlterField(
            model_name='tourimage',
            name='tours',
            field=models.ManyToManyField(blank=True, related_name='images', related_query_name='image', to='raidchileapp.Tour'),
        ),
    ]
