# Generated by Django 2.1.7 on 2019-05-06 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raidchileapp', '0003_auto_20190418_1822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourimage',
            options={'ordering': ('created_at',), 'verbose_name': 'tour image', 'verbose_name_plural': 'tour images'},
        ),
    ]
