# Generated by Django 2.1.7 on 2019-04-06 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raidchileapp', '0004_auto_20190406_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='short_desc',
            field=models.TextField(blank=True, max_length=200, verbose_name='short description'),
        ),
    ]
