# Generated by Django 2.1.7 on 2019-04-10 15:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raidchileapp', '0005_category_short_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='combo',
            field=models.BooleanField(default=False, verbose_name='Is it tour combo?'),
        ),
        migrations.AddField(
            model_name='category',
            name='combo_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='combo discount'),
        ),
    ]
