# Generated by Django 2.1.7 on 2019-05-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raidchileapp', '0006_auto_20190509_1032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-rating', '-created_at'), 'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AddField(
            model_name='review',
            name='seen',
            field=models.BooleanField(default=False, verbose_name='seen'),
        ),
    ]
