# Generated by Django 2.1.7 on 2019-04-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raidchileapp', '0006_auto_20190410_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='available',
            field=models.BooleanField(default=True, verbose_name='available'),
        ),
        migrations.AlterField(
            model_name='tourimage',
            name='alternative',
            field=models.CharField(db_index=True, help_text='Image title.', max_length=150, verbose_name='alternative text'),
        ),
    ]
