# Generated by Django 2.1.7 on 2019-05-09 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raidchileapp', '0007_auto_20190509_1742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('seen', '-created_at'), 'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterField(
            model_name='review',
            name='message',
            field=models.TextField(max_length=800, verbose_name='review'),
        ),
    ]
