# Generated by Django 2.1.7 on 2019-04-11 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raidchileapp', '0007_auto_20190410_2042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Category / Combo', 'verbose_name_plural': 'Categories / Combos'},
        ),
    ]
