# Generated by Django 2.1.7 on 2019-04-09 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ('-created_at',), 'verbose_name': 'contact message', 'verbose_name_plural': 'contact messages'},
        ),
    ]
